---
name: Katherine
surname: Goode
position: "Research and Development Statistician"
address: "Sandia National Laboratories, P.O. Box 5800 MS 0829, Albuquerque, NM 87185"
phone: +1 505-844-1998
www: goodekat.github.io
email: "kjgoode@sandia.gov"
github: github.com/goodekat
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
    page_total: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(dplyr)
library(tibble)
library(vitae)
```

# Research Interests

Model Assessment, Explainable Machine Learning, Data Visualization, Random Forests, R Package Development

# Education

```{r education}
tribble(
  ~ Degree,
  ~ Year,
  ~ Institution,
  ~ Where,
  ~ Details,
  "Doctor of Philosophy, Statistics",
  "2016-2021",
  "Iowa State University",
  "Ames, IA",
  c(
    "Dissertation: Visual Diagnostics for Explaining Machine Learning Models",
    "Major Professor: Dr. Heike Hofmann"
  ),
  "Master of Science, Statistics",
  "2013-2015",
  "University of Wisconsin, Madison",
  "Madison, WI",
  " ",
  "Bachelor of Arts, Mathematics",
  "2009-2013",
  "Lawrence University",
  "Appleton, WI",
  c(
    "Graduated Magna Cum Laude",
    "Senior Capstone: An Explanation of Double-Error-Correcting BCH Codes"
  )
) %>%
  detailed_entries(Degree, Year, Institution, Where, Details)
```

# Awards

```{r awards}
tribble(
  ~Year,
  ~Award,
  ~Desc,
  2019,
  "Midwest Statistical Machine Learning Colloquium Poster Award",
  "Awarded for poster Using LIME to Interpret a Random Forest Model with an Application to Bullet Matching Data",
  2018,
  "ISU Department of Statistics Dan Mowrey Consulting Excellence Award",
  "Awarded in recognition of outstanding contributions in the area of statistical consulting while working toward a graduate degree.",
  2017,
  "ISU Department of Statistics Award for Experiential Development",
  "Presented to a graduate student for excellent performance in multiple statistical efforts (teaching and consulting) as part of the graduate program."
) %>%
  detailed_entries(Desc, Year, Award)
```

# Experience

```{r experience}
tribble(
  
  ~ Position,
  ~ Dates,
  ~ Institution,
  ~ Where,
  ~ Details,
  
  "Postdoctoral Researcher",
  "Sep 2021 - Current",
  "Statistical Sciences Department", 
  "Sandia National Laboratories",
  c(
    "Performed research on inverse models with functional data",
    "Implemented shape analysis methods with national security data",
    "Prepared manuscript for submission to peer reviewed journal"
  ), 
  
  "Research and Development Intern",
  "Dec 2019 - Sep 2021",
  "Statistical Sciences Department",
  "Sandia National Laboratories",
  c(
    "Performed research on neural networks explainability with functional data",
    "Applied explainability methods to machine learning models",
    "Presented on work at internal and external events"
  ),
  
  "Graduate Research Assistant",
  "Jan 2021 - June 2021",
  "Natural Resource Ecology and Management",
  "Iowa State University",
  c(
    "Developed R Shiny application to predict taxonomy of fish eggs using random forests",
    "Assisted in writing manuscript to present the application",
    "Advised by Dr. Michael Weber and Dr. Philip Dixon"
  ),
  
  "Statistical Consultant",
  "May 2016 - Dec 2020",
  "Agriculture Experiment Station",
  "Iowa State University",
  c(
    "Senior consultant from May 2018 to May 2020",
    "Helped with administrative decisions and trained new consultants",
    "Provided statistical support on research projects for graduate students, professors, and staff from the colleges of agriculture and life sciences, engineering, human sciences, liberal arts and sciences, and veterinary medicine",
    "Assisted with the implementation of analyses in R, SAS, JMP, and SPSS"
  ),
  
  "Graduate Research Assistant",
  "May 2019 - Aug 2019",
  "Department Natural Resource Ecology and Management", 
  "Iowa State University",
  c(
    "Assisted with analysis of toxicology study of monarch butterfly larvae exposed to insecticides",
    "Wrote R code to compute profile confidence intervals for dose response curve models",
    "Collaboration with Dr. Steven Bradbury and PhD Student Niranjana Krishnan"
  ),
  
  "Data Analyst",
  "2015",
  "Research Administration Office", 
  "Lawrence University",
  c(
    "Analyzed data from a study to compare the academic success and mood towards the university of undergraduates from freshman to sophomore years",
    "Performed statistical analyses using SPSS"
  ),

  "Data Collection Assistant",
  "Sep 2014 May 2015",
  "Research Administration Office",
  "Lawrence University",
  c(
    "Assisted with the data collection for a study on the evaluation of warning lights installed at a busy crosswalk on the university campus",
    "Used Tracker software to determine the deceleration rate of vehicles from videos taken of cars approaching the crosswalk"
  )

) %>%
  detailed_entries(Institution, Dates, Position, Where, Details)
```

# Publications

```{r}
bibliography_entries("papers.bib") %>%
  arrange(desc(issued), author$family)
```

# Talks

```{r}
bibliography_entries("talks.bib") %>%
  arrange(desc(issued), author$family)
```
